from flask import Blueprint, request, jsonify, Response
from utils.auth_utils import token_required, get_current_user
from services.ai_service import ai_service
from utils.validators import sanitize_string
import io

summary_bp = Blueprint('summary', __name__)


@summary_bp.route('', methods=['POST'])
@token_required
def summarize():
    """Generate AI summary of a topic or text."""
    user = get_current_user()
    data = request.get_json()
    if not data:
        return jsonify({'error': 'No data provided'}), 400

    topic = data.get('topic', '').strip()
    text = data.get('text', '').strip()
    content = topic or text

    if not content:
        return jsonify({'error': 'Topic or text is required'}), 400
    if len(content) > 5000:
        return jsonify({'error': 'Content too long (max 5000 characters)'}), 400

    content = sanitize_string(content, 5000)

    result = ai_service.summarize_topic(content)

    return jsonify({
        'summary': result['summary'],
        'topic': topic or 'Custom Text',
        'tokens_used': result.get('tokens', 0)
    }), 200


@summary_bp.route('/export-pdf', methods=['POST'])
@token_required
def export_pdf():
    """Export summary as PDF."""
    data = request.get_json()
    if not data:
        return jsonify({'error': 'No data provided'}), 400

    summary_text = data.get('summary', '')
    topic = data.get('topic', 'Study Notes')

    if not summary_text:
        return jsonify({'error': 'Summary content is required'}), 400

    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
        from reportlab.lib.enums import TA_CENTER, TA_LEFT

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=inch,
            leftMargin=inch,
            topMargin=inch,
            bottomMargin=inch
        )

        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Title'],
            fontSize=24,
            spaceAfter=12,
            textColor=colors.HexColor('#6C63FF'),
            alignment=TA_CENTER
        )
        story.append(Paragraph(f"Study Notes: {topic}", title_style))
        story.append(Spacer(1, 0.2 * inch))

        # Subtitle
        subtitle_style = ParagraphStyle(
            'Subtitle',
            parent=styles['Normal'],
            fontSize=10,
            textColor=colors.gray,
            alignment=TA_CENTER
        )
        story.append(Paragraph("Generated by AI Learning Buddy | SDG 4 - Quality Education", subtitle_style))
        story.append(Spacer(1, 0.3 * inch))

        # Content
        body_style = ParagraphStyle(
            'Body',
            parent=styles['Normal'],
            fontSize=11,
            spaceAfter=8,
            leading=16
        )

        # Process markdown-like formatting
        lines = summary_text.split('\n')
        for line in lines:
            if line.startswith('## '):
                h2 = ParagraphStyle('H2', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor('#6C63FF'))
                story.append(Paragraph(line[3:], h2))
            elif line.startswith('### '):
                h3 = ParagraphStyle('H3', parent=styles['Heading3'], fontSize=12, textColor=colors.HexColor('#9C8FFF'))
                story.append(Paragraph(line[4:], h3))
            elif line.startswith('- ') or line.startswith('• '):
                bullet_style = ParagraphStyle('Bullet', parent=styles['Normal'], fontSize=11,
                                              leftIndent=20, spaceAfter=4)
                text = line[2:].replace('**', '<b>').replace('**', '</b>')
                story.append(Paragraph(f"• {line[2:]}", bullet_style))
            elif line.strip():
                clean_line = line.replace('**', '<b>').replace('**', '</b>')
                story.append(Paragraph(line, body_style))
            else:
                story.append(Spacer(1, 0.1 * inch))

        doc.build(story)
        buffer.seek(0)

        return Response(
            buffer.getvalue(),
            mimetype='application/pdf',
            headers={
                'Content-Disposition': f'attachment; filename=study_notes_{topic.replace(" ", "_")}.pdf',
                'Content-Type': 'application/pdf'
            }
        )
    except ImportError:
        return jsonify({'error': 'PDF generation not available. Install reportlab.'}), 500
    except Exception as e:
        return jsonify({'error': f'PDF generation failed: {str(e)}'}), 500
